# Generated by Django 4.2 on 2023-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooks',
            name='count_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='count page'),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date creating'),
        ),
    ]
