# Generated by Django 4.2 on 2023-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allbooks_count_page_allbooks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooks',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manual date'),
        ),
    ]
