version: "3.9"
services:
  postgres:
    image: postgres:12.14
    environment:
      POSTGRES_DB: "books_db"
      POSTGRES_USER: "book_admin"
      POSTGRES_PASSWORD: "book_admin"
      PGDATA: "/data/postgres"
    volumes:
       - "postgres:/data/postgres"
    ports:
      - "6543:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: